# Site settings
title: Dmitry Serdyuk
email: serdyuk dot dmitriy at gmail dot com
description: > 
  Dmitry Serdyuk's personal page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmitriy-serdyuk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
